### PR TITLE
Try to fix dumpsys command

### PR DESCRIPTION
**Pull request by vvb2060**
The dumpsys command does not work with root.
Device: Nexus 6P Stock ROM 7.1.2-N2G47O 
default

### CODE REVIEW

**Comment by liudongmiao** [comment]
Suggest to squash to one commit.

**Comment by aviraxp** [comment]
@topjohnwu Sorry to pin you here, but we need to get this work. Any status on this?

**Comment by liudongmiao** [comment]
@topjohnwu It's a problem like this. 

Brevent requires some result for `dumpsys`.
For example, `dumpsys notification`, `dumpsys activity activities`. 

However, in MagiskSu, dumpsys doesn't work.
You can check it with `dumpsys battery` (maybe the shortest output if success).

Brevent requires this, and I think other apps may need this

**Comment by liudongmiao** [comment]
@topjohnwu 

Are you so busy, without any response in 2 month?
Fix, or not fix, without any word?

**Review by ted-dev-42 — APPROVED** [review]

**Comment by ted-dev-42** [comment]
@topjohnwu
please merge this fix ASAP, thanks.

**Review by andylizi — APPROVED** [review]

**Pull request closed without merging**
